export const SITE_COPY = {
  ar: {
    nav: { home: "البداية", services: "الحلول", portfolio: "الأعمال", about: "عالم LENA", ai: "الأنظمة الذكية", contact: "ابدأ مشروعك", dashboard: "لوحة التحكم", start: "لنتحدث" },
    common: { explore: "اكتشف عالم LENA", viewWork: "عرض الأعمال", contact: "ابدأ مشروعك", empty: "لا توجد بيانات للعرض حاليًا.", theme: "تبديل المظهر", language: "English" },
    home: { eyebrow: "LENA DIGITAL HOUSE — CREATIVE SYSTEMS & EXPERIENCES", title: "نصنع حضورًا رقميًا", titleAccent: "لا يُنسى", intro: "نحوّل الأفكار إلى تجارب والهويات إلى حضور والخدمات إلى أنظمة واضحة يثق بها العملاء.", capabilities: "عوالم نصممها بعناية", capabilitiesIntro: "حلول مترابطة تبدأ من الهدف وتصل إلى تجربة كاملة.", work: "LENA ORIGINALS", workIntro: "مشاريع مصممة كأنظمة متكاملة، لا كبطاقات عرض.", ctaTitle: "لديك فكرة تستحق ظهورًا أفضل؟", ctaText: "ابدأ برسالة قصيرة، ونرتب الفكرة ونحدد أوضح خطوة تالية." },
    services: { eyebrow: "الحلول", title: "كل ما يحتاجه الحضور الرقمي — تحت سقف واحد", intro: "اختر أي مسار لتجد قيمته ومخرجاته وخطوات العمل والمشاريع المرتبطة به." },
    portfolio: { eyebrow: "الأعمال المختارة", title: "مشاريع غنية بالمحتوى، مبنية كرحلات قابلة للاستكشاف", intro: "تجمع LENA Originals بين الهوية والمحتوى والواجهات والأنظمة لتوضيح كيف تعمل الحلول معًا.", empty: "لا توجد مشاريع منشورة حاليًا." },
    about: { eyebrow: "عالم LENA", title: "نرى ما وراء الفكرة، ثم نبني لها عالمًا كاملًا", intro: "LENA Digital House مساحة إبداعية تجمع التخطيط والتصميم والمحتوى والتقنية في مسار واحد.", approachTitle: "كيف نعمل", approach: ["نبدأ بالهدف قبل الشكل", "نبني نظامًا متماسكًا", "نوازن بين السحر البصري وسهولة الاستخدام", "نصمم للتوسع من أول خطوة"] },
    ai: { eyebrow: "الأنظمة الذكية", title: "أتمتة وذكاء اصطناعي يحوّلان التكرار إلى تدفق واضح", intro: "نبدأ من المشكلة التشغيلية ثم نبني أداة أو تدفقًا أو لوحة متابعة تقلل الخطوات اليدوية وتوضح الإجراء التالي.", empty: "حلول مرتبطة بالتشغيل والمتابعة واتخاذ القرار." },
    contact: { eyebrow: "ابدأ مشروعك", title: "كل مشروع مميز يبدأ بمحادثة واضحة", intro: "أرسل فكرة مختصرة أو استخدم واتساب أو البريد للتواصل المباشر.", call: "اتصال", whatsapp: "واتساب", email: "البريد الإلكتروني", notConfigured: "تُضبط بيانات التواصل من إعدادات النشر." },
    footer: { description: "بيت للحلول الرقمية الإبداعية: استراتيجية وتصميم ومحتوى ومواقع ومنتجات رقمية وأتمتة.", links: "روابط سريعة", contact: "ابدأ المحادثة", rights: "جميع الحقوق محفوظة." },
    dashboard: { title: "لوحة تحكم LENA", subtitle: "إدارة الاستفسارات والمحتوى", inquiries: "الاستفسارات", portfolio: "المشاريع والأعمال", content: "المحتوى", empty: "لا توجد بيانات للعرض حاليًا." },
  },
  en: {
    nav: { home: "Opening", services: "Solutions", portfolio: "Selected Work", about: "Inside LENA", ai: "Smart Systems", contact: "Start a Project", dashboard: "Dashboard", start: "Let's Talk" },
    common: { explore: "Enter LENA", viewWork: "View Work", contact: "Start a Project", empty: "There is no data to display yet.", theme: "Toggle theme", language: "العربية" },
    home: { eyebrow: "LENA DIGITAL HOUSE — CREATIVE SYSTEMS & EXPERIENCES", title: "We create digital presence", titleAccent: "worth remembering", intro: "Ideas become experiences, identities become presence, and services become clear systems that earn trust.", capabilities: "Worlds designed with intent", capabilitiesIntro: "Connected solutions moving from goal to complete experience.", work: "LENA ORIGINALS", workIntro: "Projects designed as complete systems, not display cards.", ctaTitle: "Have an idea that deserves a stronger presence?", ctaText: "Start with a short message. We structure the idea and define the clearest next step." },
    services: { eyebrow: "Solutions", title: "Everything a digital presence needs — under one roof", intro: "Choose a track to explore its value, outputs, process, and related work." },
    portfolio: { eyebrow: "Selected Work", title: "Rich projects built as journeys worth exploring", intro: "LENA Originals connect identity, content, interfaces, and systems to show how solutions work together.", empty: "No projects are published yet." },
    about: { eyebrow: "Inside LENA", title: "We see beyond the idea, then build a world around it", intro: "LENA Digital House connects strategy, design, content, and technology into one creative path.", approachTitle: "How we work", approach: ["Start with the goal before the surface", "Build coherent systems", "Balance visual magic with usability", "Design for growth from the first step"] },
    ai: { eyebrow: "Smart Systems", title: "Automation and AI turning repetition into a clear flow", intro: "We start from the operational issue, then build a tool, workflow, or dashboard reducing manual steps and clarifying the next action.", empty: "Solutions connected to operations, follow-up, and decision making." },
    contact: { eyebrow: "Start a Project", title: "Every meaningful project starts with a clear conversation", intro: "Share a short brief or reach us directly by WhatsApp or email.", call: "Call", whatsapp: "WhatsApp", email: "Email", notConfigured: "Contact details are configured through deployment settings." },
    footer: { description: "A creative digital house for strategy, design, content, websites, digital products, and automation.", links: "Quick Links", contact: "Start the conversation", rights: "All rights reserved." },
    dashboard: { title: "LENA Dashboard", subtitle: "Manage inquiries and content", inquiries: "Inquiries", portfolio: "Projects and Work", content: "Content", empty: "There is no data to display yet." },
  },
} as const;

export type SiteLocale = keyof typeof SITE_COPY;
