export const SITE_COPY = {
  ar: {
    nav: {
      home: "الرئيسية",
      services: "الخدمات",
      portfolio: "الأعمال",
      about: "من أنا",
      ai: "حلول الذكاء الاصطناعي",
      contact: "تواصل معي",
      dashboard: "لوحة التحكم",
      start: "ابدأ مشروعك",
    },
    common: {
      explore: "استكشف الخدمات",
      viewWork: "عرض الأعمال",
      contact: "تواصل معي",
      empty: "سيتم إضافة المحتوى قريبًا.",
      theme: "تبديل المظهر",
      language: "English",
    },
    home: {
      eyebrow: "MOHAMED MASOUD — DIGITAL PLATFORM",
      title: "أحوّل الأفكار إلى",
      titleAccent: "حلول رقمية واضحة",
      intro: "منصة شخصية لعرض الخدمات والمشاريع الرقمية بصورة منظمة، وبناء حلول عملية تناسب احتياج كل مشروع.",
      capabilities: "مجالات العمل",
      capabilitiesIntro: "خدمات مترابطة تساعد على تحويل الفكرة إلى حضور رقمي متكامل.",
      work: "الأعمال",
      workIntro: "ستظهر هنا المشاريع الفعلية بعد تجهيزها وإضافتها من لوحة التحكم.",
      ctaTitle: "لديك مشروع يحتاج إلى بداية مرتبة؟",
      ctaText: "يمكننا تحديد الاحتياج ونطاق التنفيذ والخطوة التالية بوضوح.",
    },
    services: {
      eyebrow: "الخدمات",
      title: "حلول رقمية قابلة للتخصيص",
      intro: "يتم تحديد نطاق كل خدمة بعد فهم الهدف والاحتياج الفعلي للمشروع.",
    },
    portfolio: {
      eyebrow: "الأعمال",
      title: "مشاريع وأعمال مختارة",
      intro: "مساحة مخصصة لعرض المشاريع الفعلية فقط، بدون نماذج أو بيانات وهمية.",
      empty: "لم تتم إضافة مشاريع بعد.",
    },
    about: {
      eyebrow: "من أنا",
      title: "Mohamed Masoud",
      intro: "أعمل على تطوير وتنظيم حلول رقمية تجمع بين البرمجة والتصميم والتسويق وإدارة المحتوى بحسب احتياج المشروع.",
      approachTitle: "طريقة العمل",
      approach: ["فهم الهدف قبل التنفيذ", "تنظيم الأولويات والنطاق", "بناء حل واضح قابل للتطوير"],
    },
    ai: {
      eyebrow: "حلول الذكاء الاصطناعي",
      title: "مسار مستقل للحلول الذكية",
      intro: "صفحة مستقلة لعرض الخدمات المرتبطة بالأتمتة والحلول الذكية عند تجهيزها، بدون خلطها بباقي مجالات العمل.",
      empty: "سيتم إضافة تفاصيل هذا المسار قريبًا.",
    },
    contact: {
      eyebrow: "تواصل معي",
      title: "ابدأ الحديث عن مشروعك",
      intro: "تواصل مباشرة عبر الهاتف أو واتساب، وسيتم تحديد الخطوة التالية وفق طبيعة الطلب.",
      call: "اتصال",
      whatsapp: "واتساب",
      notConfigured: "تُضبط بيانات التواصل من إعدادات النشر.",
    },
    footer: {
      description: "منصة شخصية لعرض الخدمات والمشاريع الرقمية بصورة واضحة ومنظمة.",
      links: "روابط سريعة",
      contact: "التواصل",
      rights: "جميع الحقوق محفوظة.",
    },
    dashboard: {
      title: "لوحة التحكم",
      subtitle: "إدارة الاستفسارات والمحتوى",
      inquiries: "الاستفسارات",
      portfolio: "المشاريع والأعمال",
      content: "المحتوى",
      empty: "لا توجد بيانات للعرض حاليًا.",
    },
  },
  en: {
    nav: {
      home: "Home",
      services: "Services",
      portfolio: "Work",
      about: "About",
      ai: "AI Solutions",
      contact: "Contact",
      dashboard: "Dashboard",
      start: "Start a Project",
    },
    common: {
      explore: "Explore Services",
      viewWork: "View Work",
      contact: "Contact Me",
      empty: "Content will be added soon.",
      theme: "Toggle theme",
      language: "العربية",
    },
    home: {
      eyebrow: "MOHAMED MASOUD — DIGITAL PLATFORM",
      title: "Turning ideas into",
      titleAccent: "clear digital solutions",
      intro: "A personal platform for presenting digital services and projects clearly, and for building practical solutions around each project's real needs.",
      capabilities: "Capabilities",
      capabilitiesIntro: "Connected services that help transform an idea into a complete digital presence.",
      work: "Selected Work",
      workIntro: "Real projects will appear here after they are prepared and added from the dashboard.",
      ctaTitle: "Have a project that needs a structured start?",
      ctaText: "We can define the need, execution scope, and next step clearly.",
    },
    services: {
      eyebrow: "Services",
      title: "Customizable digital solutions",
      intro: "Each service scope is defined after understanding the project's objective and actual needs.",
    },
    portfolio: {
      eyebrow: "Work",
      title: "Selected projects and work",
      intro: "A dedicated space for real projects only, without sample or fabricated data.",
      empty: "No projects have been added yet.",
    },
    about: {
      eyebrow: "About",
      title: "Mohamed Masoud",
      intro: "I work on developing and organizing digital solutions that combine programming, design, marketing, and content management according to each project's needs.",
      approachTitle: "Working approach",
      approach: ["Understand the objective before execution", "Organize priorities and scope", "Build a clear and scalable solution"],
    },
    ai: {
      eyebrow: "AI Solutions",
      title: "A separate track for intelligent solutions",
      intro: "A dedicated page for automation and intelligent solutions once they are ready, without mixing them into the other service areas.",
      empty: "Details for this track will be added soon.",
    },
    contact: {
      eyebrow: "Contact",
      title: "Start the conversation about your project",
      intro: "Reach out directly by phone or WhatsApp. The next step will be defined according to the nature of the request.",
      call: "Call",
      whatsapp: "WhatsApp",
      notConfigured: "Contact details are configured through deployment settings.",
    },
    footer: {
      description: "A personal platform for presenting digital services and projects clearly and professionally.",
      links: "Quick Links",
      contact: "Contact",
      rights: "All rights reserved.",
    },
    dashboard: {
      title: "Dashboard",
      subtitle: "Manage inquiries and content",
      inquiries: "Inquiries",
      portfolio: "Projects and Work",
      content: "Content",
      empty: "There is no data to display yet.",
    },
  },
} as const;

export type SiteLocale = keyof typeof SITE_COPY;
