import { ArrowDown, ArrowUpRight } from "lucide-react";
import { Link } from "react-router";
import LenaCta from "@/components/LenaCta";
import ServiceGrid from "@/components/ServiceGrid";
import { STUDIO_PROJECTS } from "@/content/projects";
import DigitalHouseOrbit from "@/features/home/DigitalHouseOrbit";
import ProcessSection from "@/features/home/ProcessSection";
import ProjectCard from "@/features/projects/ProjectCard";
import PublicShell from "@/layouts/PublicShell";
import { usePreferences } from "@/providers/preferences";

export default function Home() { const { locale } = usePreferences(); return <PublicShell><section className="lena-hero lena-container"><div><p className="lena-kicker">LENA DIGITAL HOUSE — CREATIVE SYSTEMS & EXPERIENCES</p><h1>{locale === "ar" ? <>نصنع حضورًا رقميًا <span>لا يُنسى</span></> : <>We create digital presence <span>worth remembering</span></>}</h1><p className="lena-lead">{locale === "ar" ? "نحوّل الأفكار إلى تجارب والهويات إلى حضور والخدمات إلى أنظمة واضحة يثق بها العملاء. من الاتجاه الأول إلى أدق تفصيلة، نبني مسارًا متكاملًا قابلًا للنمو." : "Ideas become experiences, identities become presence, and services become clear systems that earn trust. From first direction to final detail, we build an integrated path made to grow."}</p><div className="lena-actions"><Link className="lena-primary" to="/services">{locale === "ar" ? "اكتشف عالم LENA" : "Enter LENA"}<ArrowUpRight size={16} /></Link><Link className="lena-secondary" to="/portfolio">{locale === "ar" ? "شاهد الأعمال" : "View work"}</Link></div><a className="lena-scroll" href="#solutions"><ArrowDown size={15} />{locale === "ar" ? "تمهّل… واكتشف العالم" : "Slow down… enter the world"}</a></div><DigitalHouseOrbit /></section><section className="lena-section" id="solutions"><div className="lena-container"><p className="lena-kicker">{locale === "ar" ? "عوالم نصممها بعناية" : "Worlds designed with intent"}</p><h2 className="lena-section-title">{locale === "ar" ? "حلول مترابطة تبدأ من الهدف وتصل إلى تجربة كاملة" : "Connected solutions moving from goal to complete experience"}</h2><p className="lena-section-lead">{locale === "ar" ? "كل بطاقة تمثل مسارًا قابلًا للدمج مع المسارات الأخرى حسب احتياج المشروع." : "Each card represents a track that can connect with the others according to the project need."}</p><ServiceGrid limit={6} showcase /></div></section><section className="lena-section"><div className="lena-container"><p className="lena-kicker">LENA ORIGINALS</p><h2 className="lena-section-title">{locale === "ar" ? "مشاريع مصممة كأنظمة متكاملة، لا كبطاقات عرض" : "Projects designed as complete systems, not display cards"}</h2><div className="lena-bento lena-project-grid">{STUDIO_PROJECTS.slice(0, 4).map((project, index) => <ProjectCard key={project.id} project={project} featured={index === 0} />)}</div></div></section><ProcessSection /><LenaCta /></PublicShell>; }
