import { useState, type ChangeEvent, type FormEvent } from "react";
import { ArrowLeft, Eye, FileImage, FolderKanban, Loader2, Pencil, Plus, Save, Send, Trash2, Upload, X } from "lucide-react";
import { Link } from "react-router";
import AppShell from "@/components/AppShell";
import { useAuth } from "@/hooks/useAuth";
import { uploadProjectMedia } from "@/lib/uploadProjectMedia";
import { usePreferences } from "@/providers/preferences";
import { trpc } from "@/providers/trpc";
import "./projects-cms.css";

type ProjectStatus = "draft" | "published" | "archived";
type LocalizedText = { ar: string; en: string };
type ProjectForm = {
  title: string; slug: string; summary: string; description: string; imageUrl: string; projectUrl: string; repositoryUrl: string; status: ProjectStatus; sortOrder: number;
  overviewAr: string; overviewEn: string; challengeAr: string; challengeEn: string; directionAr: string; directionEn: string; solutionAr: string; solutionEn: string;
  featuresAr: string; featuresEn: string; journeyAr: string; journeyEn: string; galleryUrls: string; relatedServices: string;
};
const EMPTY: ProjectForm = { title: "", slug: "", summary: "", description: "", imageUrl: "", projectUrl: "", repositoryUrl: "", status: "draft", sortOrder: 0, overviewAr: "", overviewEn: "", challengeAr: "", challengeEn: "", directionAr: "", directionEn: "", solutionAr: "", solutionEn: "", featuresAr: "", featuresEn: "", journeyAr: "", journeyEn: "", galleryUrls: "", relatedServices: "" };
const lines = (value: string) => value.split("\n").map((item) => item.trim()).filter(Boolean);
const commaList = (value: string) => value.split(",").map((item) => item.trim()).filter(Boolean);
const localized = (ar: string, en: string): LocalizedText | undefined => ar.trim() || en.trim() ? { ar: ar.trim(), en: en.trim() } : undefined;
const copy = {
  ar: { eyebrow: "LENA CMS", title: "إدارة المشاريع ودراسات الحالة", intro: "حرّر بيانات المشروع وأقسام دراسة الحالة وارفع الصور وراجع المعاينة قبل النشر.", back: "العودة إلى لوحة التحكم", portfolio: "فتح معرض الأعمال", list: "المشاريع الحالية", newProject: "مشروع جديد", editor: "محرر المشروع", preview: "المعاينة قبل النشر", basic: "البيانات الأساسية", caseStudy: "أقسام دراسة الحالة", media: "الصور والخدمات", titleField: "عنوان المشروع", slug: "المعرّف المختصر", summary: "الملخص", description: "الوصف الكامل", overview: "نظرة عامة", challenge: "المشكلة", direction: "الاتجاه الإبداعي", solution: "الحل", features: "الميزات — عنصر في كل سطر", journey: "الرحلة — خطوة في كل سطر", ar: "العربية", en: "English", image: "صورة الغلاف", gallery: "روابط صور Gallery — رابط في كل سطر", relatedServices: "الخدمات المرتبطة — مفصولة بفواصل", uploadCover: "رفع غلاف", uploadGallery: "إضافة صورة Gallery", projectUrl: "رابط المشروع", repositoryUrl: "رابط المستودع", sortOrder: "الترتيب", draft: "حفظ كمسودة", publish: "حفظ ونشر", cancel: "إلغاء التعديل", edit: "تعديل", remove: "حذف", empty: "لا توجد مشاريع بعد.", loading: "جارٍ تحميل المشاريع...", uploadFailed: "تعذر رفع الملف.", saveFailed: "تعذر حفظ المشروع.", confirmDelete: "هل تريد حذف هذا المشروع نهائيًا؟", unauthorized: "لا تملك صلاحية الوصول إلى لوحة الإدارة.", status: { draft: "مسودة", published: "منشور", archived: "مؤرشف" } },
  en: { eyebrow: "LENA CMS", title: "Projects and case studies manager", intro: "Edit project data and case-study sections, upload images, and review the preview before publishing.", back: "Back to dashboard", portfolio: "Open portfolio", list: "Current projects", newProject: "New project", editor: "Project editor", preview: "Preview before publishing", basic: "Basic information", caseStudy: "Case-study sections", media: "Media and services", titleField: "Project title", slug: "Slug", summary: "Summary", description: "Full description", overview: "Overview", challenge: "Challenge", direction: "Creative direction", solution: "Solution", features: "Features — one item per line", journey: "Journey — one step per line", ar: "Arabic", en: "English", image: "Cover image", gallery: "Gallery image URLs — one URL per line", relatedServices: "Related service IDs — comma-separated", uploadCover: "Upload cover", uploadGallery: "Add gallery image", projectUrl: "Project URL", repositoryUrl: "Repository URL", sortOrder: "Sort order", draft: "Save draft", publish: "Save and publish", cancel: "Cancel editing", edit: "Edit", remove: "Delete", empty: "No projects yet.", loading: "Loading projects...", uploadFailed: "Unable to upload file.", saveFailed: "Unable to save project.", confirmDelete: "Delete this project permanently?", unauthorized: "You do not have access to the admin dashboard.", status: { draft: "Draft", published: "Published", archived: "Archived" } },
} as const;

export default function ProjectsCms() {
  const { locale } = usePreferences(); const text = copy[locale];
  const { user, isAdmin, isLoading } = useAuth({ redirectOnUnauthenticated: true });
  const [form, setForm] = useState<ProjectForm>(EMPTY); const [editingId, setEditingId] = useState<number | null>(null);
  const [uploading, setUploading] = useState<"cover" | "gallery" | null>(null); const [error, setError] = useState("");
  const utils = trpc.useUtils(); const projects = trpc.projects.list.useQuery(undefined, { enabled: isAdmin });
  const reset = () => { setEditingId(null); setForm(EMPTY); setError(""); };
  const done = async () => { await utils.projects.invalidate(); reset(); };
  const createProject = trpc.projects.create.useMutation({ onSuccess: done, onError: () => setError(text.saveFailed) });
  const updateProject = trpc.projects.update.useMutation({ onSuccess: done, onError: () => setError(text.saveFailed) });
  const deleteProject = trpc.projects.delete.useMutation({ onSuccess: () => utils.projects.invalidate() });
  const pending = createProject.isPending || updateProject.isPending;
  function payload(status: ProjectStatus) { const featuresAr = lines(form.featuresAr); const featuresEn = lines(form.featuresEn); const journeyAr = lines(form.journeyAr); const journeyEn = lines(form.journeyEn); return { title: form.title, slug: form.slug, summary: form.summary || undefined, description: form.description || undefined, imageUrl: form.imageUrl || undefined, projectUrl: form.projectUrl || undefined, repositoryUrl: form.repositoryUrl || undefined, status, sortOrder: form.sortOrder, contentBlocks: { overview: localized(form.overviewAr, form.overviewEn), challenge: localized(form.challengeAr, form.challengeEn), direction: localized(form.directionAr, form.directionEn), solution: localized(form.solutionAr, form.solutionEn), features: featuresAr.length || featuresEn.length ? { ar: featuresAr, en: featuresEn } : undefined, journey: journeyAr.length || journeyEn.length ? { ar: journeyAr, en: journeyEn } : undefined }, gallery: lines(form.galleryUrls).map((url) => ({ url })), relatedServices: commaList(form.relatedServices) }; }
  function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = payload(form.status); if (editingId) updateProject.mutate({ id: editingId, ...data }); else createProject.mutate(data); }
  function saveAs(status: ProjectStatus) { const data = payload(status); if (!form.title || !form.slug) return; if (editingId) updateProject.mutate({ id: editingId, ...data }); else createProject.mutate(data); }
  async function upload(event: ChangeEvent<HTMLInputElement>, target: "cover" | "gallery") { const file = event.target.files?.[0]; if (!file) return; setUploading(target); setError(""); try { const imageUrl = await uploadProjectMedia(file); setForm((current) => target === "cover" ? { ...current, imageUrl } : { ...current, galleryUrls: [...lines(current.galleryUrls), imageUrl].join("\n") }); } catch { setError(text.uploadFailed); } finally { setUploading(null); event.target.value = ""; } }
  function edit(project: NonNullable<typeof projects.data>[number]) { const blocks = project.contentBlocks; setEditingId(project.id); setForm({ title: project.title, slug: project.slug, summary: project.summary ?? "", description: project.description ?? "", imageUrl: project.imageUrl ?? "", projectUrl: project.projectUrl ?? "", repositoryUrl: project.repositoryUrl ?? "", status: project.status, sortOrder: project.sortOrder, overviewAr: blocks.overview?.ar ?? "", overviewEn: blocks.overview?.en ?? "", challengeAr: blocks.challenge?.ar ?? "", challengeEn: blocks.challenge?.en ?? "", directionAr: blocks.direction?.ar ?? "", directionEn: blocks.direction?.en ?? "", solutionAr: blocks.solution?.ar ?? "", solutionEn: blocks.solution?.en ?? "", featuresAr: blocks.features?.ar.join("\n") ?? "", featuresEn: blocks.features?.en.join("\n") ?? "", journeyAr: blocks.journey?.ar.join("\n") ?? "", journeyEn: blocks.journey?.en.join("\n") ?? "", galleryUrls: project.gallery.map((item) => item.url).join("\n"), relatedServices: project.relatedServices.join(", ") }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  if (isLoading) return <AppShell><main className="cms-page"><div className="cms-empty"><Loader2 className="cms-spin" />{text.loading}</div></main></AppShell>;
  if (!user || !isAdmin) return <AppShell><main className="cms-page"><div className="cms-empty">{text.unauthorized}</div></main></AppShell>;
  return <AppShell><main className="cms-page"><div className="cms-container">
    <header className="cms-header"><div><p>{text.eyebrow}</p><h1>{text.title}</h1><span>{text.intro}</span></div><nav><Link to="/dashboard"><ArrowLeft size={16} />{text.back}</Link><Link to="/portfolio" target="_blank"><Eye size={16} />{text.portfolio}</Link></nav></header>
    <div className="cms-grid"><section className="cms-panel"><div className="cms-panel-title"><div><p>{editingId ? text.editor : text.newProject}</p><h2>{form.title || text.editor}</h2></div>{editingId && <button type="button" onClick={reset}><X size={16} />{text.cancel}</button>}</div>
      <form onSubmit={save} className="cms-form"><h3 className="wide cms-form-section">{text.basic}</h3><label><span>{text.titleField}</span><input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><label><span>{text.slug}</span><input required dir="ltr" value={form.slug} onChange={(event) => setForm({ ...form, slug: event.target.value })} /></label><label className="wide"><span>{text.summary}</span><textarea value={form.summary} onChange={(event) => setForm({ ...form, summary: event.target.value })} /></label><label className="wide"><span>{text.description}</span><textarea rows={4} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label>
      <h3 className="wide cms-form-section">{text.caseStudy}</h3>{([["overviewAr", "overviewEn", text.overview], ["challengeAr", "challengeEn", text.challenge], ["directionAr", "directionEn", text.direction], ["solutionAr", "solutionEn", text.solution]] as const).map(([arKey, enKey, label]) => <div className="wide cms-localized-grid" key={arKey}><label><span>{label} — {text.ar}</span><textarea value={form[arKey]} onChange={(event) => setForm({ ...form, [arKey]: event.target.value })} /></label><label><span>{label} — {text.en}</span><textarea dir="ltr" value={form[enKey]} onChange={(event) => setForm({ ...form, [enKey]: event.target.value })} /></label></div>)}<label><span>{text.features} — {text.ar}</span><textarea value={form.featuresAr} onChange={(event) => setForm({ ...form, featuresAr: event.target.value })} /></label><label><span>{text.features} — {text.en}</span><textarea dir="ltr" value={form.featuresEn} onChange={(event) => setForm({ ...form, featuresEn: event.target.value })} /></label><label><span>{text.journey} — {text.ar}</span><textarea value={form.journeyAr} onChange={(event) => setForm({ ...form, journeyAr: event.target.value })} /></label><label><span>{text.journey} — {text.en}</span><textarea dir="ltr" value={form.journeyEn} onChange={(event) => setForm({ ...form, journeyEn: event.target.value })} /></label>
      <h3 className="wide cms-form-section">{text.media}</h3><label><span>{text.image}</span><input dir="ltr" value={form.imageUrl} onChange={(event) => setForm({ ...form, imageUrl: event.target.value })} /></label><label className="cms-upload"><span>{text.uploadCover}</span><input type="file" accept="image/*" onChange={(event) => upload(event, "cover")} /><b>{uploading === "cover" ? <Loader2 className="cms-spin" size={16} /> : <Upload size={16} />}{text.uploadCover}</b></label><label className="wide"><span>{text.gallery}</span><textarea dir="ltr" rows={4} value={form.galleryUrls} onChange={(event) => setForm({ ...form, galleryUrls: event.target.value })} /></label><label className="cms-upload wide"><span>{text.uploadGallery}</span><input type="file" accept="image/*" onChange={(event) => upload(event, "gallery")} /><b>{uploading === "gallery" ? <Loader2 className="cms-spin" size={16} /> : <Upload size={16} />}{text.uploadGallery}</b></label><label className="wide"><span>{text.relatedServices}</span><input dir="ltr" value={form.relatedServices} onChange={(event) => setForm({ ...form, relatedServices: event.target.value })} /></label><label><span>{text.projectUrl}</span><input type="url" dir="ltr" value={form.projectUrl} onChange={(event) => setForm({ ...form, projectUrl: event.target.value })} /></label><label><span>{text.repositoryUrl}</span><input type="url" dir="ltr" value={form.repositoryUrl} onChange={(event) => setForm({ ...form, repositoryUrl: event.target.value })} /></label><label><span>{text.sortOrder}</span><input type="number" min="0" value={form.sortOrder} onChange={(event) => setForm({ ...form, sortOrder: Number(event.target.value) })} /></label><div className="cms-actions wide"><button type="button" disabled={pending} onClick={() => saveAs("draft")}><Save size={16} />{text.draft}</button><button type="button" className="primary" disabled={pending} onClick={() => saveAs("published")}><Send size={16} />{text.publish}</button></div>{error && <p className="cms-error wide">{error}</p>}</form>
    </section><aside className="cms-panel cms-preview"><p>{text.preview}</p><article>{form.imageUrl ? <img src={form.imageUrl} alt="" /> : <div className="cms-placeholder"><FileImage size={32} /></div>}<div><small>{text.status[form.status]}</small><h2>{form.title || text.titleField}</h2><p>{form.summary || text.summary}</p></div></article></aside></div>
    <section className="cms-panel cms-list"><div className="cms-panel-title"><div><p>LENA CMS</p><h2>{text.list}</h2></div><button type="button" onClick={reset}><Plus size={16} />{text.newProject}</button></div>{projects.isLoading ? <div className="cms-empty">{text.loading}</div> : projects.data?.length ? <div className="cms-records">{projects.data.map((project) => <article key={project.id}><div className="cms-thumb">{project.imageUrl ? <img src={project.imageUrl} alt="" /> : <FolderKanban size={20} />}</div><div><small>{text.status[project.status]}</small><h3>{project.title}</h3><p>{project.summary || project.description || project.slug}</p></div><nav><button type="button" onClick={() => edit(project)}><Pencil size={15} />{text.edit}</button><button type="button" className="danger" onClick={() => window.confirm(text.confirmDelete) && deleteProject.mutate({ id: project.id })}><Trash2 size={15} />{text.remove}</button></nav></article>)}</div> : <div className="cms-empty">{text.empty}</div>}</section>
  </div></main></AppShell>;
}
