import { useState, type ChangeEvent, type FormEvent } from "react";
import { ArrowLeft, Eye, FileImage, FolderKanban, Loader2, Pencil, Plus, Save, Send, Trash2, Upload, X } from "lucide-react";
import { Link } from "react-router";
import AppShell from "@/components/AppShell";
import { useAuth } from "@/hooks/useAuth";
import { uploadProjectMedia } from "@/lib/uploadProjectMedia";
import { usePreferences } from "@/providers/preferences";
import { trpc } from "@/providers/trpc";
import "./projects-cms.css";

type ProjectStatus = "draft" | "published" | "archived";
type ProjectForm = { title: string; slug: string; summary: string; description: string; imageUrl: string; projectUrl: string; repositoryUrl: string; status: ProjectStatus; sortOrder: number };
const EMPTY: ProjectForm = { title: "", slug: "", summary: "", description: "", imageUrl: "", projectUrl: "", repositoryUrl: "", status: "draft", sortOrder: 0 };
const copy = {
  ar: { eyebrow: "LENA CMS", title: "إدارة المشاريع ودراسات الحالة", intro: "حرّر بيانات المشروع وارفع صورة الغلاف وراجع المعاينة قبل النشر.", back: "العودة إلى لوحة التحكم", portfolio: "فتح معرض الأعمال", list: "المشاريع الحالية", newProject: "مشروع جديد", editor: "محرر المشروع", preview: "المعاينة قبل النشر", titleField: "عنوان المشروع", slug: "المعرّف المختصر", summary: "الملخص", description: "الوصف الكامل", image: "صورة الغلاف", upload: "رفع صورة", projectUrl: "رابط المشروع", repositoryUrl: "رابط المستودع", sortOrder: "الترتيب", draft: "حفظ كمسودة", publish: "حفظ ونشر", cancel: "إلغاء التعديل", edit: "تعديل", remove: "حذف", empty: "لا توجد مشاريع بعد.", loading: "جارٍ تحميل المشاريع...", uploadFailed: "تعذر رفع الملف.", saveFailed: "تعذر حفظ المشروع.", confirmDelete: "هل تريد حذف هذا المشروع نهائيًا؟", unauthorized: "لا تملك صلاحية الوصول إلى لوحة الإدارة.", status: { draft: "مسودة", published: "منشور", archived: "مؤرشف" } },
  en: { eyebrow: "LENA CMS", title: "Projects and case studies manager", intro: "Edit project data, upload the cover image, and review the preview before publishing.", back: "Back to dashboard", portfolio: "Open portfolio", list: "Current projects", newProject: "New project", editor: "Project editor", preview: "Preview before publishing", titleField: "Project title", slug: "Slug", summary: "Summary", description: "Full description", image: "Cover image", upload: "Upload image", projectUrl: "Project URL", repositoryUrl: "Repository URL", sortOrder: "Sort order", draft: "Save draft", publish: "Save and publish", cancel: "Cancel editing", edit: "Edit", remove: "Delete", empty: "No projects yet.", loading: "Loading projects...", uploadFailed: "Unable to upload file.", saveFailed: "Unable to save project.", confirmDelete: "Delete this project permanently?", unauthorized: "You do not have access to the admin dashboard.", status: { draft: "Draft", published: "Published", archived: "Archived" } },
} as const;

export default function ProjectsCms() {
  const { locale } = usePreferences(); const text = copy[locale];
  const { user, isAdmin, isLoading } = useAuth({ redirectOnUnauthenticated: true });
  const [form, setForm] = useState<ProjectForm>(EMPTY); const [editingId, setEditingId] = useState<number | null>(null);
  const [uploading, setUploading] = useState(false); const [error, setError] = useState("");
  const utils = trpc.useUtils(); const projects = trpc.projects.list.useQuery(undefined, { enabled: isAdmin });
  const reset = () => { setEditingId(null); setForm(EMPTY); setError(""); };
  const done = async () => { await utils.projects.invalidate(); reset(); };
  const createProject = trpc.projects.create.useMutation({ onSuccess: done, onError: () => setError(text.saveFailed) });
  const updateProject = trpc.projects.update.useMutation({ onSuccess: done, onError: () => setError(text.saveFailed) });
  const deleteProject = trpc.projects.delete.useMutation({ onSuccess: () => utils.projects.invalidate() });
  const pending = createProject.isPending || updateProject.isPending;
  function payload(status: ProjectStatus) { return { ...form, status, summary: form.summary || undefined, description: form.description || undefined, imageUrl: form.imageUrl || undefined, projectUrl: form.projectUrl || undefined, repositoryUrl: form.repositoryUrl || undefined }; }
  function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = payload(form.status); if (editingId) updateProject.mutate({ id: editingId, ...data }); else createProject.mutate(data); }
  function saveAs(status: ProjectStatus) { const data = payload(status); if (!form.title || !form.slug) return; if (editingId) updateProject.mutate({ id: editingId, ...data }); else createProject.mutate(data); }
  async function upload(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file) return; setUploading(true); setError(""); try { const imageUrl = await uploadProjectMedia(file); setForm((current) => ({ ...current, imageUrl })); } catch { setError(text.uploadFailed); } finally { setUploading(false); event.target.value = ""; } }
  function edit(project: NonNullable<typeof projects.data>[number]) { setEditingId(project.id); setForm({ title: project.title, slug: project.slug, summary: project.summary ?? "", description: project.description ?? "", imageUrl: project.imageUrl ?? "", projectUrl: project.projectUrl ?? "", repositoryUrl: project.repositoryUrl ?? "", status: project.status, sortOrder: project.sortOrder }); window.scrollTo({ top: 0, behavior: "smooth" }); }
  if (isLoading) return <AppShell><main className="cms-page"><div className="cms-empty"><Loader2 className="cms-spin" />{text.loading}</div></main></AppShell>;
  if (!user || !isAdmin) return <AppShell><main className="cms-page"><div className="cms-empty">{text.unauthorized}</div></main></AppShell>;
  return <AppShell><main className="cms-page"><div className="cms-container">
    <header className="cms-header"><div><p>{text.eyebrow}</p><h1>{text.title}</h1><span>{text.intro}</span></div><nav><Link to="/dashboard"><ArrowLeft size={16} />{text.back}</Link><Link to="/portfolio" target="_blank"><Eye size={16} />{text.portfolio}</Link></nav></header>
    <div className="cms-grid"><section className="cms-panel"><div className="cms-panel-title"><div><p>{editingId ? text.editor : text.newProject}</p><h2>{form.title || text.editor}</h2></div>{editingId && <button type="button" onClick={reset}><X size={16} />{text.cancel}</button>}</div>
      <form onSubmit={save} className="cms-form"><label><span>{text.titleField}</span><input required value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})}/></label><label><span>{text.slug}</span><input required dir="ltr" value={form.slug} onChange={(e)=>setForm({...form,slug:e.target.value})}/></label><label className="wide"><span>{text.summary}</span><textarea value={form.summary} onChange={(e)=>setForm({...form,summary:e.target.value})}/></label><label className="wide"><span>{text.description}</span><textarea rows={6} value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})}/></label><label><span>{text.image}</span><input dir="ltr" value={form.imageUrl} onChange={(e)=>setForm({...form,imageUrl:e.target.value})}/></label><label className="cms-upload"><span>{text.upload}</span><input type="file" accept="image/*" onChange={upload}/><b>{uploading ? <Loader2 className="cms-spin" size={16}/> : <Upload size={16}/>} {text.upload}</b></label><label><span>{text.projectUrl}</span><input type="url" dir="ltr" value={form.projectUrl} onChange={(e)=>setForm({...form,projectUrl:e.target.value})}/></label><label><span>{text.repositoryUrl}</span><input type="url" dir="ltr" value={form.repositoryUrl} onChange={(e)=>setForm({...form,repositoryUrl:e.target.value})}/></label><label><span>{text.sortOrder}</span><input type="number" min="0" value={form.sortOrder} onChange={(e)=>setForm({...form,sortOrder:Number(e.target.value)})}/></label><div className="cms-actions wide"><button type="button" disabled={pending} onClick={()=>saveAs("draft")}><Save size={16}/>{text.draft}</button><button type="button" className="primary" disabled={pending} onClick={()=>saveAs("published")}><Send size={16}/>{text.publish}</button></div>{error && <p className="cms-error wide">{error}</p>}</form>
    </section><aside className="cms-panel cms-preview"><p>{text.preview}</p><article>{form.imageUrl ? <img src={form.imageUrl} alt=""/> : <div className="cms-placeholder"><FileImage size={32}/></div>}<div><small>{text.status[form.status]}</small><h2>{form.title || text.titleField}</h2><p>{form.summary || text.summary}</p></div></article></aside></div>
    <section className="cms-panel cms-list"><div className="cms-panel-title"><div><p>LENA CMS</p><h2>{text.list}</h2></div><button type="button" onClick={reset}><Plus size={16}/>{text.newProject}</button></div>{projects.isLoading ? <div className="cms-empty">{text.loading}</div> : projects.data?.length ? <div className="cms-records">{projects.data.map((project)=><article key={project.id}><div className="cms-thumb">{project.imageUrl ? <img src={project.imageUrl} alt=""/> : <FolderKanban size={20}/>}</div><div><small>{text.status[project.status]}</small><h3>{project.title}</h3><p>{project.summary || project.description || project.slug}</p></div><nav><button type="button" onClick={()=>edit(project)}><Pencil size={15}/>{text.edit}</button><button type="button" className="danger" onClick={()=>window.confirm(text.confirmDelete)&&deleteProject.mutate({id:project.id})}><Trash2 size={15}/>{text.remove}</button></nav></article>)}</div> : <div className="cms-empty">{text.empty}</div>}</section>
  </div></main></AppShell>;
}
